name: sandc_pos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  dio: ^4.0.4
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.3.1
  url_launcher: ^6.0.20
  flutter_speed_dial: ^5.1.0
  flutter_datetime_picker: ^1.5.1
  carousel_slider: ^4.0.0
  awesome_dialog: ^2.2.1
  firebase_core: ^1.13.1
  firebase_messaging: ^11.4.0
  firebase_database: ^9.0.14
  cloud_firestore: ^3.1.15
  modal_bottom_sheet: ^2.0.1
  get: ^4.6.5
  responsive_grid: ^2.1.0
  horizontal_data_table: ^4.1.2+2
  qr_code_scanner: ^1.0.1
  dropdown_search: ^5.0.3
  flutter_svg: ^1.1.5
  sqflite: ^2.1.0
  uuid: ^3.0.6
  pdf:
  printing:
  custom_pop_up_menu: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/Jannah.ttf
